apiVersion: v1
kind: Service
metadata:
  name: {{ include "builder.fullname" . }}
  labels:
    {{- include "builder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and .Values.service.type (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "builder.selectorLabels" . | nindent 4 }}
