name: PR validation
on:
  pull_request: null
  workflow_dispatch: null
jobs:
  validate-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Setup KinD
        uses: helm/kind-action@v1.10.0
        with:
          install_only: true
      - name: Test project
        run: ./gradlew check
      - name: End 2 end tests
        run: ./gradlew cucumberTest
      - name: Load tests
        run: ./gradlew runGatling
