name: Release sample app
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          token:  ${{ secrets.PUSH_FRAUCA_TOKEN }}
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica' # Default buildpack distribution
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set git config
        run: |
          git config --global user.email "fraucamidokura@noreply.com"
          git config --global user.name "fraucamidokura"
          git config -l
      - name: Make new release
        run: ./gradlew release -Prelease.useAutomaticVersion=true